### PR TITLE
edit contact page

### PR DESCRIPTION
**Pull request by Essien-MS**

### CODE REVIEW

**Comment by Essien-MS** [comment]
e

**Comment by Mersharch** [comment]
pull the new changes ive made and redo your changes please

**Comment by Mersharch** [comment]
pull the new changes ive made and redo your edits please

**Comment by Mersharch** [comment]
pull the new changes ive made and redo your edits please

**Comment by Mersharch** [comment]
pull the new changes ive made and redo your edits please

**Pull request closed without merging**
